repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    - id: check-added-large-files
      name: check-added-large-files
      description: Prevent giant files from being committed.
    - id: check-merge-conflict
      name: check-merge-conflict
      description: Check for files that contain merge conflict strings.
    - id: check-symlinks
      name: check-symlinks
      description: Checks for symlinks which do not point to anything.
    - id: detect-private-key
      name: detect-private-key
      description: Checks for the existence of private keys.
    - id: end-of-file-fixer
      name: end-of-file-fixer
      description: Makes sure files end in a newline and only a newline.
    - id: trailing-whitespace
      name: trailing-whitespace
      description: Trims trailing whitespace
    - id: requirements-txt-fixer
      name: requirements-txt-fixer
      description: Sorts entries in requirements.txt
      args: [
        "requirements/development.txt", "requirements/production.txt"
      ]
#  - repo: https://github.com/psf/black
#    rev: stable
#    hooks:
#      - id: black
#        language_version: python3.7
#  - repo: https://gitlab.com/pycqa/flake8
#    rev: 3.8.3
#    hooks:
#    - id: flake8
#      additional_dependencies: [
#        'flake8-blind-except',
#        'flake8-bugbear',
#        'flake8-coding',
#        'flake8-commas',
#        'flake8-debugger',
#        'flake8-docstrings',
#        'flake8-isort',
#        'flake8-quotes',
#        'flake8-sfs',
#        'flake8-string-format',
#      ]
#  - repo: https://github.com/timothycrosley/isort
#    rev: 4.3.21
#    hooks:
#    - id: isort
#      name: isort
#      entry: isort
#      require_serial: true
#      language: python
#      types: [python]
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: 'v0.780'
#    hooks:
#    - id: mypy
