"""Initial migrations

Revision ID: eea1fb837486
Revises: 
Create Date: 2020-06-12 12:18:02.558146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eea1fb837486"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
