"""Initial

Revision ID: e6206c32187e
Revises: 6699549f7ca3
Create Date: 2022-05-31 15:03:19.476414

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e6206c32187e'
down_revision = '6699549f7ca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('age', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_plant_age'), 'plant', ['age'], unique=False)
    op.create_index(op.f('ix_plant_name'), 'plant', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plant_name'), table_name='plant')
    op.drop_index(op.f('ix_plant_age'), table_name='plant')
    op.drop_column('plant', 'age')
    # ### end Alembic commands ###
